### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by davidhunter08**
Adding new icons:
- calendar
- clock
- download 
- email
- filter
- letter
- night
- phone call
- sort

image

### CODE REVIEW

**Comment by davidhunter08** [comment]
`calendar` icon name should probably be `add-calendar`?

**Comment by davidhunter08** [comment]
@edwardscull how do you think we should handle the colour of the icons?

All previous icons have been blue but some of the new icons (clock, night and phone call) need to be black.

Example:
image

**Comment by edwardscull** [comment]
> @edwardscull how do you think we should handle the colour of the icons?
> 
> All previous icons have been blue but some of the new icons (clock, night and phone call) need to be black.
> 
> Example: image

Have we confirmed whether we need to support both blue and black?

**Comment by davidhunter08** [comment]
> > @edwardscull how do you think we should handle the colour of the icons?
> > All previous icons have been blue but some of the new icons (clock, night and phone call) need to be black.
> > Example: image
> 
> Have we confirmed whether we need to support both blue and black?

Yes. I've added a modifier class `nhsapp-icon-black`.

**Review by edwardscull — APPROVED** [review]

**Pull request merged**
