### PR TITLE
Update component guidance

### PR DESCRIPTION
**Pull request by davidhunter08**
Updating the component guidance to let teams know they can iterate components (if there is a need to) and share any changes with us in GitHub.

| Before | After |
| -------|-------|
| old | new |

### CODE REVIEW

**Review by michaelgallagher — APPROVED** [review]
approved

**Review by Graham-Pembrey — CHANGES_REQUESTED** [review]
Looks great! One small suggestion. Could we change:

`Existing design components can be used as starting points but may need to be iterated to suit the needs of users of a particular service.`

To be in the active voice:

`You can use existing components as starting points, but you may need to iterate them to meet user needs for particular services.`

**Comment by davidhunter08** [comment]
Thanks @Graham-Pembrey, I've updated the content 👍

Screenshot 2024-12-03 at 09 10 08

**Review by Graham-Pembrey — APPROVED** [review]
Thanks Dave. Looks good

**Pull request merged**
