### PR TITLE
Add panel component

### PR DESCRIPTION
**Pull request by davidhunter08**
## Description

Adding the panel component (for [confirmation pages](https://github.com/nhsuk/nhsapp-frontend/issues/32)).

## To do
- [x] add scss
- [x] add macro
- [x] add examples
- [x] add guidance page

Also need to add vue.js and Figma links once they've been created.

### CODE REVIEW

**Comment by davidhunter08** [comment]
@Graham-Pembrey the guidance is ready to review 👀

**Comment by davidhunter08** [comment]
@edwardscull NHS.UK frontend component macros call a [attributes.njk](https://github.com/nhsuk/nhsuk-frontend/blob/main/packages/macros/attributes.njk)

Probably something we should include in the NHS App macros?

**Review by Graham-Pembrey — APPROVED** [review]
Looks good to me. As a next update, we could consider adding a 'Research' section with a summary of recent findings. Panels have tested well as part of confirmation pages, including with two participants who had colour vision deficiency (colour blindness).

**Review by edwardscull — APPROVED** [review]
👍

**Pull request merged**
